# Site
name: "Stat Mania"
title: "Stat Mania Blog"
description: "পরিসংখ্যান কী ও কেন? পরিসংখ্যান আমাদের জীবনে কীভাবে কাজে লাগে? মেশিন লার্নিংয়ের সাথে পরিসংখ্যানের কী সম্পর্ক? সহজে কীভাবে পরিসংখ্যান বুঝব? এমনসব বিষয় নিয়েই সাজানো হয়েছে ওয়েবসাইটটি।"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: ''
disqus: mahmudblog
mailchimp-list: 'https://github.us7.list-manage.com/subscribe/post?u=fb245679a93a6d0bd6681211b&amp;id=f02c47251c'
include: ["_pages"]
permalink: /:title.sm

# Authors
authors:
  mahmud:
    name: Abdullah Al Mahmud
    display_name: Abdullah Al Mahmud    
    avatar: 'assets/images/authors/mahmud.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: almahmud.sbi@gmail.com
    web: https://mahmud.statmania.info/
    twitter: https://twitter.com/
    description: "Lecturer in statistics at PCC"
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
